# .github/workflows/crawl.yml
name: Crawl Exchange Rate

on:
  schedule:
    - cron: '0 * * * *'  # chạy mỗi giờ
  workflow_dispatch:      # cho phép chạy thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run crawler
        run: |
          node crawl.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git commit -m "Update exchange rate $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
