# .github/workflows/crawl.yml
name: Crawl CoinGecko Prices

on:
  schedule:
    - cron: '0 * * * *' # mỗi giờ
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm init -y

      - name: Run crawl script
        run: node crawl.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add prices.json
          git commit -m "Update coin prices $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
